# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f80e2810925abf12d03c9e220374bef5f83c93d6e33e05465d55ac9f136c26ced8b8b64e1f18fa23786485116304a7581f9c77a7dd1f01f8f206ee0b7912023e

test:
  secret_key_base: 74704f7bf1b0cc425704e61ca30dc7d235f8060341b77d3212b015efea2f0d194d7c53642d0b08e0e0374a1587a68e426b12e3de44ece2ed29a74261b5228d41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
